manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/PercyJW-2
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: zmk-modules
      url-base: https://github.com/PercyJW-2
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-ws2812-gpio-backport
      remote: zmk-modules
      revision: main
  self:
    path: config
